Revert "Hookup GRALLOC_HANDLE_HAS_RESERVED_SIZE"
This reverts commit cec5a9cadf7d433c237a501a5ac7c38059080975.

error: vendor/qcom/opensource/commonsys-intf/display/Android.bp:4:1: "display_intf_headers" depends on undefined module "gralloc_handle_has_reserved_size_defaults"

Change-Id: 758d42b47afe8b1836060ff791cdbff8dc6579a9
Signed-off-by: TogoFire <italomellopereira@gmail.com>